---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart zed
  ansible.builtin.systemd_service:
    name: zfs-zed
    state: restarted

# inet_interfaces only changes on a restart.
- name: Restart postfix
  ansible.builtin.systemd_service:
    name: postfix
    state: restarted

- name: Reload postfix
  ansible.builtin.systemd_service:
    name: postfix
    state: reloaded
