---
- name: Restart pveproxy and spiceproxy
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
  loop:
    - pveproxy
    - spiceproxy

- name: Update initramfs
  ansible.builtin.command:
    cmd: update-initramfs -u -k all
  changed_when: true

- name: Apply network changes
  ansible.builtin.command:
    cmd: pvesh set /nodes/{{ ansible_facts.hostname }}/network
  changed_when: true
